apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
  namespace: cicd-neotys
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: gold